services:
  nginx:
    build: ./nginx/
    ports:
      - "8080:443"
    profiles: [
      "prod"
    ]
    secrets:
      - ssl_key
      - ssl_crt
  vite:
    build: ./vite/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/frontend/
      - shared:/app/shared/
      - babylonjs-toolkit:/app/@babylonjs-toolkit/
    profiles: [
      "dev"
    ]
    secrets:
      - ssl_key
      - ssl_crt
  fastify:
    build: ./fastify/
    volumes:
      - backend:/app/dev/
      - databases:/app/databases/
      - babylonjs-toolkit:/app/@babylonjs-toolkit/
    profiles: [
      "prod",
      "dev"
    ]

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/dev/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ../src/backend/dev/
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: ../src/shared/
      o: bind
  babylonjs-toolkit:
    driver: local
    driver_opts:
      type: none
      device: ../@babylonjs-toolkit/
      o: bind
  databases:
    driver: local

secrets:
  ssl_crt:
    file: ./secrets/ssl/selfsigned.crt
  ssl_key:
    file: ./secrets/ssl/selfsigned.key
