services:
  nginx:
    build: ./nginx/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/public/
    profiles: [
      "prod"
    ]
  vite:
    build: ./vite/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/public/
    profiles: [
      "dev"
    ]
  fastify:
    build: ./fastify/
    volumes:
      - backend:/app/backend/
      - databases:/app/databases/
    profiles: [
      "prod",
      "dev"
    ]

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/public/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ../src/backend/
      o: bind
  databases:
    driver: local
