services:
  fastify:
    build: ./fastify/
    volumes:
      - backend:/app/dev/
      - databases:/app/databases/
    environment:
      - PROFILE=${PROFILE:-prod} 
    profiles: [
      "prod",
      "dev"
    ]
    env_file:
      - ./.env.fastify_example
  nginx:
    build: ./nginx/
    ports:
      - "8080:443"
    profiles: [
      "prod"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify
  vite:
    build: ./vite/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/frontend/
      - shared:/app/shared/
    profiles: [
      "dev"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/dev/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ./fastify/app_src/dev/
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: ../src/shared/
      o: bind
  databases:
    driver: local

secrets:
  ssl_crt:
    file: ./secrets/ssl/selfsigned.crt
  ssl_key:
    file: ./secrets/ssl/selfsigned.key
