services:
  nginx:
    build: ./nginx/
    ports:
      - "8080:443"
    profiles: [
      "prod"
    ]
    secrets:
      - ssl_key
      - ssl_crt
  vite:
    build: ./vite/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/public/
    profiles: [
      "dev"
    ]
    secrets:
      - ssl_key
      - ssl_crt
  fastify:
    build: ./fastify/
    volumes:
      - backend:/app/backend/
      - databases:/app/databases/
      - uploads:/app/uploads/
    environment:
      - PROFILE=${PROFILE:-prod} 
    profiles: [
      "prod",
      "dev"
    ]
    ports:
      - "8181:8181"
    env_file:
      - ./.env.fastify_example

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/dev/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ../src/backend/
      o: bind
  databases:
    driver: local
  uploads: 
    driver: local

secrets:
  ssl_crt:
    file: ./secrets/ssl/selfsigned.crt
  ssl_key:
    file: ./secrets/ssl/selfsigned.key
