services:
  nginx:
    build: ./nginx/
    ports:
      - "8080:8080"
    volumes:
      - frontend:/app/
  fastify:
    build: ./fastify/
    ports:
      - "8181:8181"
    volumes:
      - backend:/app/backend/

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/public/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ../src/backend/
      o: bind
