services:
  fastify:
    build: ./fastify/
    volumes:
      - backend:/app/dev/
      - databases:/app/databases/
    environment:
      - PROFILE=${PROFILE:-prod} 
    profiles: [
      "prod",
      "dev"
    ]
    env_file:
      - ./fastify/app_src/.env
  nginx:
    build: ./nginx/
    ports:
      - "8080:443"
    profiles: [
      "prod"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify
  vite:
    build: ./vite/
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/frontend/
      - shared:/app/shared/
    profiles: [
      "dev"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify

volumes:
  frontend:
    driver: local
  backend:
    driver: local
  shared:
    driver: local
  databases:
    driver: local

secrets:
  ssl_crt:
    file: ./secrets/ssl/selfsigned.crt
  ssl_key:
    file: ./secrets/ssl/selfsigned.key
